# Generated by Django 4.0.3 on 2022-03-21 12:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income_or_expence', models.CharField(choices=[('支出', '支出'), ('收入', '收入')], default='支出', max_length=2)),
                ('tag_name', models.CharField(default='早餐', max_length=200, unique=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income_or_expence', models.CharField(choices=[('支出', '支出'), ('收入', '收入')], default='支出', max_length=2)),
                ('discription', models.CharField(default='Null', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2022, 3, 21))),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_web.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
