# Generated by Django 4.0.3 on 2022-03-18 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 7, 14, 2, 729964, tzinfo=utc)),
        ),
    ]
