# Generated by Django 4.0.3 on 2022-03-22 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_web', '0002_rename_income_or_expence_record_income_or_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
    ]
