# Generated by Django 4.0.3 on 2022-03-20 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_web', '0003_record_activaty_alter_record_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 20)),
        ),
    ]
