# Generated by Django 4.0.3 on 2022-03-20 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_web', '0004_remove_record_time_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
    ]
